### ISSUE TITLE
периодически отваливается плагин, помогает рестарт HA 

### ISSUE THREAD

**Issue by dsultanr** [Limych/ha-narodmon#117]
**Environment**

- Home Assistant Core release with the issue: Home Assistant 2022.10.1
- This custom component release with the issue:     "version": "2.0.3",
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Docker

**Describe the bug**

за две недели отвалился пару раз плагин, показывает Unknown, помогает рестарт HA

**Configuration.yaml**
```yaml

narodmon:
  verify_ssl: false
  devices:
    - name: "Narodmon"
      latitude: 55.661311
      longitude: 38.139066
      sensors:
        - temperature
        - pressure


```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-19 23:22:14.038 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [Connect call failed ('185.245.187.136', 443)]
2023-05-20 01:36:37.179 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-20 11:40:44.619 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2023-05-20 13:25:19.010 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [Try again]
2023-05-20 14:20:07.639 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Timeout fetching homeassistant_alerts data
2023-05-20 18:30:51.153 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-20 23:16:24.009 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [Try again]
2023-05-21 08:53:56.950 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-21 15:01:24.079 ERROR (MainThread) [custom_components.narodmon] Error fetching narodmon data:
2023-05-21 18:44:06.873 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-21 23:25:29.014 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [Try again]
2023-05-22 01:25:29.128 ERROR (MainThread) [custom_components.narodmon] Error fetching narodmon data:
2023-05-22 16:14:16.648 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-22 19:15:27.469 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2023-05-22 23:22:33.047 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [Connect call failed ('185.245.187.136', 443)]
2023-05-23 10:34:33.103 ERROR (MainThread) [custom_components.narodmon] Error fetching narodmon data:
2023-05-23 11:20:17.640 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Timeout fetching homeassistant_alerts data
2023-05-23 23:16:33.222 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-05-23 23:22:42.070 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [Connect call failed ('185.245.187.136', 443)]
^C


```

**Additional context**

![Screenshot 2023-05-24 104605](https://github.com/Limych/ha-narodmon/assets/1683476/83e19545-4172-455f-a8b6-2922bf7423be)

![Screenshot 2023-05-24 104523](https://github.com/Limych/ha-narodmon/assets/1683476/a47285ed-c9fd-44b9-b4ab-70bf6c749c8c)

**Comment by dsultanr** [comment]
any news on this?

**Comment by Myumdom** [comment]
как указать какие датчики передавать в этот нармон?

**Comment by skadiexe** [comment]
просто никак не работает. с конфигом плясал по всякому, ни один датчик не удалось получить

**Comment by dsultanr** [comment]
ну у остальных как-то работает

у меня даже отваливаться перестало после обновления HA

скидывай конфиги

вт, 27 февр. 2024 г., 12:56 Ivan Vasilev ***@***.***>:

**Comment by skadiexe** [comment]
![image](https://github.com/Limych/ha-narodmon/assets/34567532/a170c2f3-6dc0-4cb5-a581-cb84a18008b0)


```
narodmon:
  verify_ssl: false
# apikey: "----"
  devices:
    - name: "Narodmon"
      latitude: 00.12072
      longitude: 00.18236
      scan_interval: "00:20"
      sensors:
        - temperature
        - humidity
        - pressure
        - wind_speed
        - wind_bearing
#        - pm
#        - precipitation
#        - illuminance
#        - uv
#        - radiation

```

**Comment by dsultanr** [comment]
в логах смотрел?

у меня вот такой конфиг работает

![image](https://github.com/Limych/ha-narodmon/assets/1683476/d2cb410d-4ff7-4321-970a-4b0651eb790f)

плагин установлен через HACS

![image](https://github.com/Limych/ha-narodmon/assets/1683476/baf1ba12-6601-43dc-9f5b-438cfe017773)

в settings / devices вот так видно

![image](https://github.com/Limych/ha-narodmon/assets/1683476/049b2469-d267-4d18-ae0e-5c6e40c5e63d)

![image](https://github.com/Limych/ha-narodmon/assets/1683476/36ea9464-acbd-41f8-b2cb-197eb7a6c932)

**Comment by skadiexe** [comment]
ну какая-то ругань есть, но она и в погоде гисметео есть, но там все работает

```
2024-02-27 13:40:42.954 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_HUMIDITY was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.960 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_ILLUMINANCE was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ILLUMINANCE instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.965 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PRESSURE was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PRESSURE instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.971 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_TEMPERATURE was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.977 WARNING (MainThread) [homeassistant.const] LENGTH_MILLIMETERS was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.982 WARNING (MainThread) [homeassistant.const] PRESSURE_MMHG was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.MMHG instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.988 WARNING (MainThread) [homeassistant.const] SPEED_METERS_PER_SECOND was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
2024-02-27 13:40:42.993 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from narodmon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/Limych/ha-narodmon/issues
```

**Comment by skadiexe** [comment]
![image](https://github.com/Limych/ha-narodmon/assets/34567532/b0769689-c29f-41ba-9465-8dc4f78af039)

**Comment by dsultanr** [comment]
ну и? сравнил свои и мои скрины?

**Comment by skadiexe** [comment]
сравнил, но я не знаю, что ему нужно, чтобы оно начало работать. делал по инструкции, ничего сложного не увидел.

что нужно, чтобы был 1 device ? 

пробовал вручную добавить устройство -> narodmon
![image](https://github.com/Limych/ha-narodmon/assets/34567532/f49ac977-c5da-4978-9de7-cdcdea4a60ca)

но не работает. все равно 0 device

**Comment by dsultanr** [comment]
в папке custom_components есть папка narodmod?

**Comment by skadiexe** [comment]
![image](https://github.com/Limych/ha-narodmon/assets/34567532/78598288-b703-4121-9b5e-f74b9d60d413)

есть

**Comment by dsultanr** [comment]
restart HA же делал?

попробуй тут дебаг включить, перезагрузи HA и шли полный лог 
![image](https://github.com/Limych/ha-narodmon/assets/1683476/d7b87e29-7f4f-49d0-aade-ee677640e9cb)

**Comment by skadiexe** [comment]
[home-assistant_2024-02-27T18-04-00.677Z.log](https://github.com/Limych/ha-narodmon/files/14424028/home-assistant_2024-02-27T18-04-00.677Z.log)
этот лог?

**Comment by dsultanr** [comment]
похоже, но нет никаких ошибок. 

https://community.home-assistant.io/t/integrations-are-working-but-missing-from-devices-services-where-did-they-go/614434/6
вот тут пишут, что настройка через YAML и через UI это разные вещи

попробуй удалить ha-narodmon в HACS, убрать или закоменть в configuration.yaml и удалить папку в custom_components. перезагрузись и потом заново добавь плагин через HACS и больше ничего не делай, оно должно по дефолту запуститься и появиться devices. еще помню у меня была проблема из-за того, что геопозиция в настройках самого HA не была настроена

**Comment by dsultanr** [comment]
обновление HA до 2024.1.6 помогло

**Comment by skadiexe** [comment]
обновился тоже
начало ругаться на конфиг
убрал строчку scan_interval
заработало

**Comment by ildar170975** [comment]
у меня порой тупо не работает при старте, со `scan_interval` или без, а не после отваливается.
```
narodmon:
  devices:

    - name: Narodmon xxx
      latitude: xxx
      longitude: xxx
      sensors:
        - temperature
        - radiation
```
