### ISSUE TITLE
Компонент не инициализируется из-за entry.source == SOURCE_IMPORT

### ISSUE THREAD

**Issue by lemon777** [Limych/ha-narodmon#149]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.12.6
os_name | Linux
os_version | 6.6.54-current-sunxi
arch | armv7l
timezone | Asia/Aqtau
config_dir | /home/homeassistant/.homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1460
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 29, 2024 at 1:41 PM
-- | --
current_recorder_run | November 7, 2024 at 1:57 PM
estimated_db_size | 450.23 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-narodmon/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

По установке все сделал по инструкции, но девайса и сенсоров так не и появилось. Включение логирования, дебага ничего не показывало. В логах только одно сообщение от компонента

Narodmon Cloud Integration
Version: 2.2.1
This is a custom integration!
If you have ANY issues with this you need to open an issue here:
https://github.com/Limych/ha-narodmon/issues

Поэтому пришлось самостоятельно расставить дополнительные логи. В итоге не проходит условие if entry.source == SOURCE_IMPORT, потому что в моём случае entry.source является "user". Поменял во всех местах на if entry.source == "user" и интеграция заработала

### Reproduction steps

1. Have HACS installed, this will allow you to easily manage and track updates.
2. Search for "Narodmon".
3. Click Install below the found integration.
4. Сonfigure component via configuration.yaml

### Debug logs

```text
2024-11-07 13:57:45.572 INFO (MainThread) [custom_components.narodmon]
-------------------------------------------------------------------
Narodmon Cloud Integration
Version: 2.2.1
This is a custom integration!
If you have ANY issues with this you need to open an issue here:
https://github.com/Limych/ha-narodmon/issues
-------------------------------------------------------------------
2024-11-07 13:57:45.572 INFO (MainThread) [custom_components.narodmon] entry: '<ConfigEntry entry_id=01JC2HX7D3ZKXC2GM99ZWSNGD1 version=1 domain=narodmon title=Home Assistant state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>'
2024-11-07 13:57:45.578 INFO (MainThread) [custom_components.narodmon] entry.source: 'user'
2024-11-07 13:57:45.578 INFO (MainThread) [custom_components.narodmon] entry.data: '{}'
2024-11-07 13:57:45.579 INFO (MainThread) [custom_components.narodmon] YAML_DOMAIN: '_yaml_narodmon'
2024-11-07 13:57:45.579 INFO (MainThread) [custom_components.narodmon] New client
2024-11-07 13:57:45.579 INFO (MainThread) [custom_components.narodmon] Devices: [{'name': 'Narodmon', 'search_area_radius': 50.0, 'latitude': 43.295263, 'longitude': 76.937541, 'show_on_map': True, 'sensors': ['temperature', 'humidity', 'pressure'], 'scan_interval': datetime.timedelta(seconds=180)}]
2024-11-07 13:57:45.580 INFO (MainThread) [custom_components.narodmon] New coordinator for: {'name': 'Narodmon', 'search_area_radius': 50.0, 'latitude': 43.295263, 'longitude': 76.937541, 'show_on_map': True, 'sensors': ['temperature', 'humidity', 'pressure'], 'scan_interval': datetime.timedelta(seconds=180)}
2024-11-07 13:57:45.580 INFO (MainThread) [custom_components.narodmon] Init NarodmonDataUpdateCoordinator
2024-11-07 13:57:45.580 INFO (MainThread) [custom_components.narodmon] _async_update_data
2024-11-07 13:57:45.581 INFO (MainThread) [custom_components.narodmon] _async_update_data: {}
2024-11-07 13:57:45.581 INFO (MainThread) [custom_components.narodmon] tps: {1, 2, 3}
2024-11-07 13:57:46.230 INFO (MainThread) [custom_components.narodmon] coordinator.async_refreshed
2024-11-07 13:57:46.231 INFO (MainThread) [custom_components.narodmon] DOMAIN: narodmon
2024-11-07 13:57:46.231 INFO (MainThread) [custom_components.narodmon] hass.data[DOMAIN]: {'01JC2HX7D3ZKXC2GM99ZWSNGD1': {0: <custom_components.narodmon.NarodmonDataUpdateCoordinator object at 0xb4091a80>}}
2024-11-07 13:57:46.231 INFO (MainThread) [custom_components.narodmon] async_forward_entry_setups
2024-11-07 13:57:46.231 INFO (MainThread) [custom_components.narodmon] entry: <ConfigEntry entry_id=01JC2HX7D3ZKXC2GM99ZWSNGD1 version=1 domain=narodmon title=Home Assistant state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>
2024-11-07 13:57:50.675 INFO (MainThread) [homeassistant.components.sensor] Setting up narodmon.sensor
2024-11-07 13:57:50.689 INFO (MainThread) [custom_components.narodmon] async_forward_entry_setups DONE
2024-11-07 13:57:50.690 INFO (MainThread) [custom_components.narodmon] add_update_listener
```

**Comment by strk90** [comment]
Спасибо, за решение проблемы!
Тоже заменил  if entry.source == SOURCE_IMPORT на if entry.source == "user"  и все заработало.

**Comment by Limych** [comment]
> Reproduction steps
> 1. Have HACS installed, this will allow you to easily manage and track updates.
> 1. Search for "Narodmon".
> 1. Click Install below the found integration.
> 1. Сonfigure component via configuration.yaml

А приложить содержимое конфига, что, религия не позволяет?  И если Вы так всё замечательно починили, почему не прислали PR?.. Вот и делай доброе после этого людям...

**Comment by Limych** [comment]
Конфиг:
```yaml
narodmon:
  devices:
    - name: "Narodmon"
      search_area_radius: 50
      latitude: 43.295263
      longitude: 76.937541
      show_on_map: True
      sensors:
        - temperature
        - humidity
        - pressure
      scan_interval:
        seconds: 180

```
Результат работы на тестовой сборке:
![image](https://github.com/user-attachments/assets/c3f69133-ae3b-404a-9cbd-23657c0baf1c)

Баг не выявлен.

**Comment by avoronkov84** [comment]
Подтверждаю. Замена if entry.source == SOURCE_IMPORT на if entry.source == "user" в трех(!!) файлах по адресу /config/custom_components/narodmon и перезагрузка HA - сразу дала искомые датчики (без правки конфига!). До этого за сутки датчики так и не появлялись. 
Автор, прошу внести соответствующие корректировки в интеграцию. Спасибо!

**Comment by FreedomArt** [comment]
> Подтверждаю. Замена if entry.source == SOURCE_IMPORT на if entry.source == "user" в трех(!!) файлах по адресу /config/custom_components/narodmon и перезагрузка HA - сразу дала искомые датчики (без правки конфига!). До этого за сутки датчики так и не появлялись. Автор, прошу внести соответствующие корректировки в интеграцию. Спасибо!

Ни как не могу запустить:

> Регистратор: homeassistant.config_entries
Источник: config_entries.py:749
Зафиксировано первый раз: 19:43:11 (3 случая)
Зафиксировано последний раз: 20:31:33

> Error setting up entry configuration.yaml for narodmon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/narodmon/__init__.py", line 126, in async_setup_entry
    await hass.config_entries.async_remove(entry.entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2086, in async_remove
    unload_success, entry = await self._async_remove(entry_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2102, in _async_remove
    async with entry.setup_lock:
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 110, in acquire
    await fut
asyncio.exceptions.CancelledError: Global task timeout

Конфиг:
`narodmon:
  apikey: k***P
  devices:
    - name: "Narodmon"
      latitude: 11.345335
      longitude: 22.876554
      search_area_radius: 10 
      scan_interval: '01:00'
      sensors:
        - temperature
        - humidity
        - wind_speed
        - wind_bearing
        - precipitation`

**Comment by avoronkov84** [comment]
> Ни как не могу запустить:

Во всех трех файлах поправили? В одном надо в двух местах править. Итого 4 замены. 
Я без apikey делал, кстати. Вроде где-то читал, что с ним как раз и не заводится у некоторых.

**Comment by avoronkov84** [comment]
> Автор, прошу внести соответствующие корректировки в интеграцию. Спасибо!

На 2.2.2 проблема сохранилась, решение с заменой строк в 4 местах в 3 файлах так же работает.
